[project]
name = "car-price-prediction-model"
version = "0.1.0"
description = "This is a car price prediction model using various machine learning algorithms."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mlflow>=3.8.1",
    "shap>=0.49.1",
    "streamlit>=1.53.0",
]
